environment:
  matrix:
    - CMAKE_GENERATOR: "Visual Studio 11 2012"
      MPI_HOME: "C:/Program Files (x86)/Microsoft SDKs/MPI"
    - CMAKE_GENERATOR: "Visual Studio 12 2013"
      MPI_HOME: "C:/Program Files (x86)/Microsoft SDKs/MPI"
    - CMAKE_GENERATOR: "Visual Studio 14 2015"
      MPI_HOME: "C:/Program Files (x86)/Microsoft SDKs/MPI"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: "Visual Studio 15 2017"
      MPI_HOME: "C:/Program Files (x86)/Microsoft SDKs/MPI"

install:
  - ps: Start-FileDownload 'https://github.com/Microsoft/Microsoft-MPI/releases/download/v10.0/msmpisetup.exe'
  - MSMpiSetup.exe -unattend
  - set PATH=C:\Program Files\Microsoft MPI\Bin;%PATH%
  - ps: Start-FileDownload 'https://github.com/Microsoft/Microsoft-MPI/releases/download/v10.0/msmpisdk.msi'
  - msmpisdk.msi /passive

build_script:
  - ps: Start-FileDownload 'https://github.com/01org/tbb/releases/download/2019_U3/tbb2019_20181203oss_win.zip'
  - unzip tbb2019_20181203oss_win.zip
  - tbb2019_20181203oss\bin\tbbvars.bat intel64
  - cmd: python scripts/lint.py
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G "%CMAKE_GENERATOR%" ^
               -DMPI_C_INCLUDE_PATH:PATH="%MPI_HOME%/Include" ^
               -DMPI_C_LIBRARIES:PATH="%MPI_HOME%/Lib/x86/msmpi.lib" ^
               -DMPI_CXX_INCLUDE_PATH:PATH="%MPI_HOME%/Include" ^
               -DMPI_CXX_LIBRARIES:PATH="%MPI_HOME%/Lib/x86/msmpi.lib" ..
  - cmd: cmake --build .
  - cmd: cd ..
  - cmd: set OMP_NUM_THREADS=4
  - cmd: run.bat
